"""empty message

Revision ID: 476303a52938
Revises: d08bb5ed7804
Create Date: 2021-12-08 21:00:14.917579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476303a52938'
down_revision = 'd08bb5ed7804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gname', sa.String(length=100), nullable=False, comment='商品名'),
    sa.Column('price', sa.Float(), nullable=False, comment='价格'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户外键'),
    sa.Column('goods_id', sa.Integer(), nullable=False, comment='商品外键'),
    sa.Column('number', sa.Integer(), nullable=True, comment='购买数量'),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_table('user_goods')
    op.drop_table('goods')
    # ### end Alembic commands ###
