"""empty message

Revision ID: d08bb5ed7804
Revises: 
Create Date: 2021-12-08 16:25:53.675282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd08bb5ed7804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('pdatetime', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('read_number', sa.Integer(), nullable=True, comment='阅读数'),
    sa.Column('collect_number', sa.Integer(), nullable=True, comment='收藏数'),
    sa.Column('fav_number', sa.Integer(), nullable=True, comment='喜欢数'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户外键'),
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='软删除'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('icon', sa.String(length=256), nullable=True, comment='头像'))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=15),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=256),
               comment='密码',
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               comment='手机',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment='email',
               existing_nullable=True)
    op.alter_column('user', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='软删除',
               existing_nullable=True)
    op.alter_column('user', 'rdatetime',
               existing_type=mysql.DATETIME(),
               comment='注册时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rdatetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='注册时间',
               existing_nullable=True)
    op.alter_column('user', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='软删除',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               comment=None,
               existing_comment='email',
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               comment=None,
               existing_comment='手机',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=256),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=15),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.drop_column('user', 'icon')
    op.drop_table('article')
    # ### end Alembic commands ###
