"""empty message

Revision ID: 50c3b2a66223
Revises: c89de972b455
Create Date: 2021-12-01 21:15:01.833188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c3b2a66223'
down_revision = 'c89de972b455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isdelete')
    # ### end Alembic commands ###
