"""empty message

Revision ID: 05aa7857b5c7
Revises: d33658751b31
Create Date: 2023-01-30 16:38:58.209860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05aa7857b5c7'
down_revision = 'd33658751b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'aboutme', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message_board', 'user', ['post_user_id'], ['id'])
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_constraint(None, 'message_board', type_='foreignkey')
    op.drop_constraint(None, 'aboutme', type_='foreignkey')
    # ### end Alembic commands ###
