"""empty message

Revision ID: c488e8dfb44d
Revises: 81ad5cfb9e64
Create Date: 2021-12-16 14:59:07.717686

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c488e8dfb44d"
down_revision = "81ad5cfb9e64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aboutme",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content", sa.BLOB(), nullable=True, comment="用户信息"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户id"),
        sa.Column("isdelete", sa.Boolean(), nullable=True, comment="软删除"),
        sa.Column("pdatetime", sa.DateTime(), nullable=True, comment="上传时间"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "photo", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "photo", type_="foreignkey")
    op.drop_table("aboutme")
    # ### end Alembic commands ###
