"""empty message

Revision ID: c63349261454
Revises: c488e8dfb44d
Create Date: 2021-12-16 17:10:35.916957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63349261454'
down_revision = 'c488e8dfb44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=False, comment='留言'),
    sa.Column('post_user_id', sa.Integer(), nullable=True, comment='评论用户id, 默认0是匿名用户'),
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('mdatetime', sa.DateTime(), nullable=True, comment='留言时间'),
    sa.ForeignKeyConstraint(['post_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'aboutme', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_constraint(None, 'aboutme', type_='foreignkey')
    op.drop_table('message_board')
    # ### end Alembic commands ###
