"""empty message

Revision ID: d33658751b31
Revises: c63349261454
Create Date: 2021-12-16 18:46:01.245646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33658751b31'
down_revision = 'c63349261454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'aboutme', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message_board', 'user', ['post_user_id'], ['id'])
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_constraint(None, 'message_board', type_='foreignkey')
    op.drop_constraint(None, 'aboutme', type_='foreignkey')
    # ### end Alembic commands ###
