"""empty message

Revision ID: 88bc5754fab3
Revises: 6df571b12882
Create Date: 2021-12-09 19:49:41.980641

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88bc5754fab3"
down_revision = "6df571b12882"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("comment", sa.String(length=255), nullable=False, comment="评论内容"),
        sa.Column("article_id", sa.Integer(), nullable=True, comment="文章外键"),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="用户外键"),
        sa.Column("cdatetime", sa.DateTime(), nullable=True, comment="评论时间"),
        sa.Column("isdelete", sa.Boolean(), nullable=True, comment="软删除"),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "user_goods", "goods", ["goods_id"], ["id"])
    op.create_foreign_key(None, "user_goods", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_goods", type_="foreignkey")
    op.drop_constraint(None, "user_goods", type_="foreignkey")
    op.drop_table("comment")
    # ### end Alembic commands ###
