"""empty message

Revision ID: 99a0709363e5
Revises: 88bc5754fab3
Create Date: 2021-12-09 19:56:20.951988

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99a0709363e5"
down_revision = "88bc5754fab3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("typename", sa.String(length=50), nullable=False, comment="分类名"),
        sa.Column("isdelete", sa.Boolean(), nullable=True, comment="软删除"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "article",
        sa.Column("type_id", sa.Integer(), nullable=False, comment="文章分类外键"),
    )
    op.create_foreign_key(None, "article", "article_type", ["type_id"], ["id"])
    op.create_foreign_key(None, "comment", "article", ["article_id"], ["id"])
    op.create_foreign_key(None, "comment", "user", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_goods", "user", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_goods", "goods", ["goods_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_goods", type_="foreignkey")
    op.drop_constraint(None, "user_goods", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "article", type_="foreignkey")
    op.drop_column("article", "type_id")
    op.drop_table("article_type")
    # ### end Alembic commands ###
