"""empty message

Revision ID: 81ad5cfb9e64
Revises: cdfdbbf0a184
Create Date: 2021-12-15 17:33:30.635961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ad5cfb9e64'
down_revision = 'cdfdbbf0a184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('isdelete', sa.Boolean(), nullable=True, comment='软删除'))
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'isdelete')
    # ### end Alembic commands ###
