"""empty message

Revision ID: cdfdbbf0a184
Revises:
Create Date: 2021-12-15 16:02:53.863639

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cdfdbbf0a184"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "article", "article_type", ["type_id"], ["id"])
    op.create_foreign_key(None, "comment", "user", ["user_id"], ["id"])
    op.create_foreign_key(None, "comment", "article", ["article_id"], ["id"])
    op.alter_column(
        "photo",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_general_ci", length=1024
        ),
        comment="图片名字,实际存放的是本地路径",
        existing_comment="图片名字",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "photo", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "photo", type_="foreignkey")
    op.alter_column(
        "photo",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_general_ci", length=1024
        ),
        comment="图片名字",
        existing_comment="图片名字,实际存放的是本地路径",
        existing_nullable=False,
    )
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "article", type_="foreignkey")
    # ### end Alembic commands ###
